include:
  - docker-compose-db.yml

services:
  goa-chatbot:
    build: .
    image: goa-chatbot:latest
    restart: always
    ports:
      - "8086:8086"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb-chatbot:27017/goachatbotdb?authSource=admin
      SPRING_SECURITY_OAUTH2_JWK-URI: http://host.docker.internal:8080/api/goa-user/oauth2/jwks
      SPRING_SECURITY_OAUTH2_TOKEN-URI: http://host.docker.internal:8080/api/goa-user/oauth2/token
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - chatbotNet

networks:
  chatbotNet:
    external: true

#> docker compose up --build -d

# Para ver los logs de arranque
#> docker logs -f goa-chatbot