spring:
  security:
    oauth2:
      jwk-uri: https://goa.miwupm.es/api/goa-user/oauth2/jwks
      token-uri: https://goa.miwupm.es/api/goa-user/oauth2/token
      api-client-id: ${API_CLIENT_ID}
      api-client-secret: ${API_CLIENT_SECRET}

  data:
    mongodb:
      uri: ${MONGODB_URI}

goa:
  user:
    base-url: https://goa.miwupm.es/api/goa-user/users
  engagement:
    base-url: https://goa.miwupm.es/api/goa-engagement

app:
  cors:
    allowed-origins: https://goa.miwupm.es

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
